name: Publish Tab

on: 
  push:
    paths:
      - "Formula/tab.rb"

    branches:    
      - master

jobs:
  tab:
    name: tab
    runs-on: macOS-latest
    # runs-on: ubuntu-latest
    steps:
      - name: Setup
        env:
          GITHUB_TOKEN: ${{secrets.HOMEBREW_GITHUB_TOKEN}}
          
        run: |
          brew tap austinjones/taps
          cd /usr/local/Homebrew/Library/Taps/austinjones/homebrew-taps
          git remote set-url origin "https://austinjones:${GITHUB_TOKEN}@github.com/austinjones/homebrew-taps.git"
          git config user.name "Github Actions/Publish Tab"
          git config user.email "implAustin+bottlebot@gmail.com"

          brew install jq
        
      - name: Bottle
        env:
          GITHUB_TOKEN: ${{secrets.HOMEBREW_GITHUB_TOKEN}}

        run: |
          cd /usr/local/Homebrew/Library/Taps/austinjones/homebrew-taps

          FORMULA=./Formula/tab.rb
          ARCHIVE=$(grep "url \"" ./Formula/tab.rb | sed -E 's/\s*url \"//g' | sed 's/\"//g' | head -n 1 | rev | cut -d '/' -f 1 | rev)
          TAG=$(echo $ARCHIVE | sed 's/.tar.gz//')
          RELEASE_ID=$(curl https://api.github.com/repos/austinjones/tab-rs/releases/tags/${TAG} | jq .id)

          curl --data-binary @"README.md" \
            "https://uploads.github.com/repos/austinjones/tab-rs/releases/$RELEASE_ID/assets?name=test-readme.md" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream"
          
          echo "Building bottle for tag ${TAG}..."
          brew install --build-bottle ./Formula/tab.rb
          brew bottle --json --root-url=https://github.com/austinjones/tab-rs/releases/download/$TAG $FORMULA
          brew bottle --merge tab--*.json --write --no-commit
          BOTTLE_FILE=$(ls tab-*.tar.gz)

          echo "Uploading bottle file $BOTTLE_FILE to the $TAG artifacts..."

          curl --data-binary @"$BOTTLE_FILE" \
            "https://uploads.github.com/repos/austinjones/tab-rs/releases/$TAG/assets?name=$BOTTLE-FILE" \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream"
          
          git add $FORMULA
          git commit -m "Build bottle for tab $TAG: $BOTTLE_FILE"
          git push origin master

          echo "Bottle published at url https://github.com/austinjones/tab-rs/releases/download/$TAG/$BOTTLE_FILE"